-- Trigger to automatically create a hostel when an admin is created
-- Generated by Antigravity

CREATE OR REPLACE FUNCTION public.handle_new_admin_hostel()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- Only create if hostel_name is provided and no hostel exists yet
    IF NEW.hostel_name IS NOT NULL AND NEW.hostel_name != '' THEN
        INSERT INTO public.hostels (admin_id, name, address, phone)
        VALUES (NEW.id, NEW.hostel_name, COALESCE(NEW.hostel_address, ''), COALESCE(NEW.phone, ''))
        ON CONFLICT DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$;

-- Drop trigger if exists to avoid duplication
DROP TRIGGER IF EXISTS on_admin_created_create_hostel ON public.admins;

-- Create Trigger
CREATE TRIGGER on_admin_created_create_hostel
    AFTER INSERT ON public.admins
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_admin_hostel();

-- Also handle updates (e.g. completing profile)
CREATE OR REPLACE FUNCTION public.handle_admin_profile_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    -- If hostel_name was null and is now set, and no hostel exists, create one
    IF OLD.hostel_name IS NULL AND NEW.hostel_name IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM public.hostels WHERE admin_id = NEW.id) THEN
            INSERT INTO public.hostels (admin_id, name, address, phone)
            VALUES (NEW.id, NEW.hostel_name, COALESCE(NEW.hostel_address, ''), COALESCE(NEW.phone, ''));
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_admin_updated_create_hostel ON public.admins;

CREATE TRIGGER on_admin_updated_create_hostel
    AFTER UPDATE ON public.admins
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_admin_profile_update();
