-- Multi-Hostel Architecture Migration
-- Generated by Antigravity

-- 1. Create Hostels Table
CREATE TABLE IF NOT EXISTS public.hostels (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    admin_id uuid REFERENCES public.admins(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    address text,
    phone text,
    logo_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.hostels ENABLE ROW LEVEL SECURITY;

-- Policies for Hostels
CREATE POLICY "Admins can manage their own hostels"
    ON public.hostels
    FOR ALL
    USING (auth.uid() = admin_id);

CREATE POLICY "Tenants can view their hostel details"
    ON public.hostels
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.tenures 
            WHERE tenures.hostel_id = hostels.id 
            AND (tenures.id = auth.uid() OR tenures.email = (select email from auth.users where id = auth.uid()))
        )
    );

-- 2. Data Migration: Move existing Admin details to Hostels table
-- We create a default hostel for every existing admin using their profile data
INSERT INTO public.hostels (admin_id, name, address, phone)
SELECT id, COALESCE(hostel_name, 'My Hostel'), hostel_address, phone
FROM public.admins
ON CONFLICT DO NOTHING; -- Safety check

-- 3. Update Child Tables to reference Hostel
-- Helper function to add column and migrate data safely
CREATE OR REPLACE FUNCTION migrate_table_to_multi_hostel(table_name text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    -- Add column if not exists
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS hostel_id uuid REFERENCES public.hostels(id) ON DELETE CASCADE', table_name);
    
    -- Populate hostel_id based on admin_id
    -- We join with hostels table on admin_id to find the correct hostel
    EXECUTE format('
        UPDATE public.%I t
        SET hostel_id = h.id
        FROM public.hostels h
        WHERE t.admin_id = h.admin_id
        AND t.hostel_id IS NULL
    ', table_name);
END;
$$;

-- Run migration for all core tables
SELECT migrate_table_to_multi_hostel('rooms');
SELECT migrate_table_to_multi_hostel('tenures');
SELECT migrate_table_to_multi_hostel('invoices');
SELECT migrate_table_to_multi_hostel('payments');
SELECT migrate_table_to_multi_hostel('complaints');
SELECT migrate_table_to_multi_hostel('expenses');
SELECT migrate_table_to_multi_hostel('community_posts');

-- 4. Update RLS Policies (Optional but recommended for strictness)
-- For now, existing RLS checks 'admin_id' which is still valid (Owner Access).
-- We will add specific policies for 'hostel_id' filtering in the Frontend, 
-- but strictly enforcing it in RLS requires updating every policy.
-- Strategy: Keep Admin-level RLS for safety, Frontend handles Hostel-level filtering.

-- 5. Add Index for Performance
CREATE INDEX IF NOT EXISTS idx_rooms_hostel_id ON public.rooms(hostel_id);
CREATE INDEX IF NOT EXISTS idx_tenures_hostel_id ON public.tenures(hostel_id);
CREATE INDEX IF NOT EXISTS idx_invoices_hostel_id ON public.invoices(hostel_id);
CREATE INDEX IF NOT EXISTS idx_payments_hostel_id ON public.payments(hostel_id);

-- 6. Cleanup Function (Optional)
DROP FUNCTION migrate_table_to_multi_hostel;
